### ISSUE TITLE
TypeError: You may only yield a function, promise, generator, array, or object, but the following object was passed: "undefined"

### ISSUE THREAD

**Issue by imomin** [vitali-ausianik/tasks-runner#30]
I get following error, when the data is fetched from the database. Any idea why?

Start processing of task "taskA" (f7fe592b-92f3-4dc0-bc77-77cdac60be5b)
Providing processor for task with name: reminder
Passed data during task scheduling: [object Object]
Result of previous task of the same group: null
Extended information about current task:  { failedAt: 2016-07-20T07:15:04.521Z,
  errorMsg: 'You may only yield a function, promise, generator, array, or object, but the following object was passed: "undefined"',
  retries: 1,
  createdAt: 2016-07-20T07:14:38.731Z }

Task was failed: "f7fe592b-92f3-4dc0-bc77-77cdac60be5b" TypeError: You may only yield a function, promise, generator, array, or object, but the following object was passed: "undefined"
    at next (/home/pi/myproject/RaspberryPI/node_modules/co/index.js:101:25)
    at onFulfilled (/home/pi/myproject/RaspberryPI/node_modules/co/index.js:69:7)
    at /home/pi/myproject/RaspberryPI/node_modules/co/index.js:54:5
    at co (/home/pi/myproject/RaspberryPI/node_modules/co/index.js:50:10)
    at toPromise (/home/pi/myproject/RaspberryPI/node_modules/co/index.js:118:63)
    at next (/home/pi/myproject/RaspberryPI/node_modules/co/index.js:99:29)
    at onFulfilled (/home/pi/myproject/RaspberryPI/node_modules/co/index.js:69:7)
    at process._tickCallback (internal/process/next_tick.js:103:7)
Task was rescheduled: {"taskId":"f7fe592b-92f3-4dc0-bc77-77cdac60be5b","startAt":"2016-07-20T07:19:53.008Z"}

**Comment by vitali-ausianik** [comment]
Could you please provide a code snippet how do you use it ? Right now it looks like your processor is no a generator and also  it doesn't return a promise. Please see [this section](https://github.com/vitali-ausianik/tasks-runner#task-processor) in readme

**Comment by imomin** [comment]
Here is the my code snippet. It is pretty much copy and paste from your "example" folder.

```

var scheduleTaskRunner = {
	taskProcessor:function(taskName){
	    console.log('Providing processor for task with name: ' + taskName);
	    switch (taskName) {
	        case 'taskA':
	            return function (data, previousTaskResult, extendedTaskInfo) {
	                console.log('Passed data during task scheduling: ' + data);
	                console.log('Result of previous task of the same group: ' + previousTaskResult);
	                console.log('Extended information about current task: ', extendedTaskInfo);
	            };
	        default:
	            throw new Error('Task processor is not defined for task: ' + taskName);
	    }
	},
	initialize:function(){
		taskRunner.connect(url);
		taskRunner.run({
		    scanInterval: 60, // 60 seconds
		    lockInterval: 60, // 60 seconds
		    tasksPerScanning: 1000,
		    taskProcessorFactory: this.taskProcessor
		}).then(function(){
		    console.log('First scanning iteration was finished');
		});

		//process.on('SIGTERM', taskRunner.stop.bind(taskRunner));
		//process.on('SIGINT', taskRunner.stop.bind(taskRunner));
	}
}
```

**Comment by vitali-ausianik** [comment]
please try to replace (difference in one symbol) 
from: `return function (data, previousTaskResult, extendedTaskInfo) {`
to: `return function* (data, previousTaskResult, extendedTaskInfo) {`

**Comment by imomin** [comment]
OK, that did it. Thanks!

**Comment by vitali-ausianik** [comment]
also you can use something like (in case if you prefer to use "promise" way)
```
return new Promise(function (data, previousTaskResult, extendedTaskInfo) {
    console.log('Passed data during task scheduling: ' + data);
    console.log('Result of previous task of the same group: ' + previousTaskResult);
    console.log('Extended information about current task: ', extendedTaskInfo);
});
```

**Comment by imomin** [comment]
OK

**Comment by vitali-ausianik** [comment]
[Added feature](https://github.com/vitali-ausianik/tasks-runner/issues/31) which makes possible to use regular functions as task processors
